component: website
name: website-RoIz__tVEx
org: '1251738879'
app: kkkv50
stage: prod
inputs:
  region: ap-guangzhou
  src:
    error: index.html
    exclude:
      - .env
    index: index.html
    src: ./
  bucketName: my-bucket-8ln9y2t
